# Generated by Django 4.0.5 on 2022-06-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
